services:
  - type: web
    name: backend
    runtime: python
    plan: free
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.0
      - key: FRONTEND_URL
        fromService:
          name: frontend
          type: web
          property: url
      - key: REDIS_URL
        fromService:
          name: redis-cache
          type: redis
          property: connectionString
      - fromGroup: backend-secrets
    buildCommand: |
      pip install -r backend/requirements.txt
      cd backend && alembic upgrade head
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
  - type: web
    name: frontend
    runtime: node
    plan: free
    healthCheckPath: /
    envVars:
      - key: NODE_VERSION
        value: 20.16.0
      - key: NEXT_PUBLIC_BACKEND_URL
        fromService:
          name: backend
          type: web
          property: url
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm start
  - type: redis
    name: redis-cache
    plan: free

  - name: backend-secrets
    envVars:
      - key: DATABASE_URL
        generateValue: true
      - key: JWT_SECRET
        generateValue: true
      - key: ALGORITHM
        value: HS256
    type: web
    runtime: docker
