"""adding type in the message class

Revision ID: 0a871865f78b
Revises: bfda180a4948
Create Date: 2025-07-09 20:17:45.722248

"""

from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "0a871865f78b"
down_revision: Union[str, Sequence[str], None] = "bfda180a4948"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "message", sa.Column("type", sqlmodel.sql.sqltypes.AutoString(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("message", "type")
    # ### end Alembic commands ###
