"""ajouter du cascade entre les messages et la conversation

Revision ID: 309500ef8f58
Revises: 77afd3d827fb
Create Date: 2025-07-15 18:51:32.946723

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "309500ef8f58"
down_revision: Union[str, Sequence[str], None] = "77afd3d827fb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("message_conversation_id_fkey"), "message", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "message", "conversation", ["conversation_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "message", type_="foreignkey")
    op.create_foreign_key(
        op.f("message_conversation_id_fkey"),
        "message",
        "conversation",
        ["conversation_id"],
        ["id"],
    )
    # ### end Alembic commands ###
