"""adding reation to message class

Revision ID: 77afd3d827fb
Revises: eb5f2606e1dd
Create Date: 2025-07-11 13:55:00.200507

"""

from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "77afd3d827fb"
down_revision: Union[str, Sequence[str], None] = "eb5f2606e1dd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "message",
        sa.Column("reaction", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.drop_column("message", "rection")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "message",
        sa.Column("rection", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_column("message", "reaction")
    # ### end Alembic commands ###
