"""jointure

Revision ID: acb955b1ee43
Revises: def6b144728c
Create Date: 2025-06-29 18:10:11.079471

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "acb955b1ee43"
down_revision: Union[str, Sequence[str], None] = "def6b144728c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("contact", sa.Column("user_id", sa.Integer(), nullable=False))
    op.drop_constraint(op.f("contact_owner_id_fkey"), "contact", type_="foreignkey")
    op.create_foreign_key(None, "contact", "user", ["user_id"], ["id"])
    op.drop_column("contact", "owner_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "contact",
        sa.Column("owner_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(str, "contact", type_="foreignkey")  # type: ignore
    op.create_foreign_key(
        op.f("contact_owner_id_fkey"), "contact", "user", ["owner_id"], ["id"]
    )
    op.drop_column("contact", "user_id")
    # ### end Alembic commands ###
